### ISSUE TITLE
프로젝트 궁금증 두가지

### ISSUE THREAD

**Issue by jongfeel** [Joseph-Cha/MeetingRoomReservationSystem#1]
README를 보고 궁금증이 2 개가 생겼는데요

첫번째로는
예약 시스템의 경우 캘린더 공유 기능을 통해 충분히 의사 소통을 할 수 있긴 합니다.
누가 어떤 시간에 예약을 했는지 캘린더를 통해 모두 볼 수 있고
시간 조정 역시 예약한 사람에게 별도로 연락해서 조정하는 방식으로 하면
굳이 예약 시스템을 만들어야 하나...? 라는 생각이 들게 됩니다

두번째로는
캘린더 공유는 알지만 개인 개발 실력 향상을 위해 만들기로 했다고 치면
unity를 webgl로 만들어야 할 이유에 대해서 생각을 해 봐야 할 필요가 있을 것 같네요.
웹에서 간단하게 예약 시스템 기능 구현하는데 굳이 unity를?
이라는 질문에 설득력 있는 대답이 나와야 할 것 같습니다.

**Comment by Joseph-Cha** [comment]
1. 우선 교회에서 사용하는 모임 장소가 정확하지는 않지만 5개 이상입니다. 해서 회의실 예약과 같은 시스템이 필요해서 해당 프로젝트를 시작하게 되었습니다!

2. 이 부분은 저도 지금도 고민 중이에요. 토이 프로젝트 성격도 있기 때문에 React로 만들면 좋을 것 같단 생각이 들기도 하지만 html, css, js 모두 모르는 상황이기 때문에 만들면서 배우기에는 시간적으로 여유가 없기도 해서요. 무튼 이 부분은 조금 더 고민을 해볼게요!

**Comment by jongfeel** [comment]
제가 왜 캘린더를 통한 예약 시스템이 좋다고 했냐 하면
제가 다녔던 여러 회사에서 회의실을 예약하는 여러 가지 방법에 대해 경험을 토대로 말씀드린 거에요.

만약 시스템을 개발해서 예약 시스템을 만들고 관리한다고 했을 때 물리적인 리소스가 소비된다는 측면에서 보자면

- 시스템을 관리하는 인력과 그 시간이 필요하고
- 시스템을 사용하는 사용자의 요구에 따라 시스템 유지보수하는데 드는 시간과 노력이 개발하는데 드는 시간과 노력에 비해 월등히, 정말 월등히 높기 때문입니다.

물론 서버 유지 비용이나 소프트웨어 라이선스 비용은 제외하고 말씀드린 거고요.

회의실이 5개라면 계정 5개 생성해서 캘린더 공유하는 방식으로 하는 걸 추천드리고
다른 프로젝트를 하시는게 어떨까요?

이 예약 시스템 만들면 나중에 "아는 사람한테 조립PC 견적 내주는 거 아님" 이라는 말이 왜 나오게 됐는지 알게 될 떄가 올겁니다.

**Comment by Joseph-Cha** [comment]
이것 저곳에 문의도 해보고 구글 캘린더로 회의실 예약을 하는 방법도 알아보니 현실적으로 적용하기는 어려울 것 같습니다.
1000명이 넘는 사람들에게 캘린더 방식을 안내하고 적용하기가 쉽지 않아 보이네요..
그리고 회장단에서 한 분이 장소 예약 문의를 받고 관리를 하고 계시는데 계정 5개 이야기를 꺼내자마자 질색을 하시는 군요..ㅋㅋ

![image](https://user-images.githubusercontent.com/75019048/160242748-19f1c9c8-2264-4f6a-a319-7383abab4ebf.png)

제가 참고한 레퍼런스입니다. 
위와 같이 장소 및 시간을 보고 예약이 가능한지 여부를 직관적으로 확인이 가능한 시스템을 만들고 싶었어요.

또한 운영적인 측면은 저도 알아보고 있지만 무료 웹 호스팅 업체를 최대한 활용해볼 예정입니다.  
그리고 DB는 구글 스프레드 시트를 활용하려고 하구요.

끝으로 관리는 끝이 어떻게 되든 일단 시작해보려고 합니다. 봉사하는 마음으로 해보려구요.
좋은 방법 제안해주셔서 감사드리고 구글 캘린더로 장소 예약도 가능하다는 것을 알게 되어 또한 기쁘네요 ㅎㅎ
나중에 분명 써먹을 일이 있을 것 같습니다.

~~https://github.com/Joseph-Cha/ConferenceReservationSystem/pull/2
그리고 살짝 늦었지만 프로젝트 개요에 대해서 간략하게 작성한 것 공유합니다.
한번 보시고 논의 이어가면 좋을 것 같아요.~~

아.. README를 이미 읽으셨군요,,?!!

**Comment by jongfeel** [comment]
아 제가 말을 잘못했는데 구글 캘린더 계정 5개는 아니고요
한 계정에 캘린더 5개를 세팅할 수 있다는 걸 잘못 얘기했군요.
